//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datapecker.Agent.ReportingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationCredentials", Namespace="http://schemas.datacontract.org/2004/07/Datapecker.Service")]
    [System.SerializableAttribute()]
    internal partial class ApplicationCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstanceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationIDField, value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string InstanceID {
            get {
                return this.InstanceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InstanceIDField, value) != true)) {
                    this.InstanceIDField = value;
                    this.RaisePropertyChanged("InstanceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SecretKey {
            get {
                return this.SecretKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretKeyField, value) != true)) {
                    this.SecretKeyField = value;
                    this.RaisePropertyChanged("SecretKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionEvent", Namespace="http://schemas.datacontract.org/2004/07/Datapecker.DAL")]
    [System.SerializableAttribute()]
    internal partial class ExceptionEvent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ClientRegisteredTimeUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Datapecker.Agent.ReportingService.ExceptionDetails> ExceptionDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Datapecker.Agent.ReportingService.ExceptionEventCase> ExceptionEventCasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmitterClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubmitterLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmitterMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmitterModuleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmitterStackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime ClientRegisteredTimeUtc {
            get {
                return this.ClientRegisteredTimeUtcField;
            }
            set {
                if ((this.ClientRegisteredTimeUtcField.Equals(value) != true)) {
                    this.ClientRegisteredTimeUtcField = value;
                    this.RaisePropertyChanged("ClientRegisteredTimeUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EventKey {
            get {
                return this.EventKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EventKeyField, value) != true)) {
                    this.EventKeyField = value;
                    this.RaisePropertyChanged("EventKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<Datapecker.Agent.ReportingService.ExceptionDetails> ExceptionDetails {
            get {
                return this.ExceptionDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionDetailsField, value) != true)) {
                    this.ExceptionDetailsField = value;
                    this.RaisePropertyChanged("ExceptionDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<Datapecker.Agent.ReportingService.ExceptionEventCase> ExceptionEventCases {
            get {
                return this.ExceptionEventCasesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionEventCasesField, value) != true)) {
                    this.ExceptionEventCasesField = value;
                    this.RaisePropertyChanged("ExceptionEventCases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SubmitterClass {
            get {
                return this.SubmitterClassField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmitterClassField, value) != true)) {
                    this.SubmitterClassField = value;
                    this.RaisePropertyChanged("SubmitterClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int SubmitterLine {
            get {
                return this.SubmitterLineField;
            }
            set {
                if ((this.SubmitterLineField.Equals(value) != true)) {
                    this.SubmitterLineField = value;
                    this.RaisePropertyChanged("SubmitterLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SubmitterMethod {
            get {
                return this.SubmitterMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmitterMethodField, value) != true)) {
                    this.SubmitterMethodField = value;
                    this.RaisePropertyChanged("SubmitterMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SubmitterModule {
            get {
                return this.SubmitterModuleField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmitterModuleField, value) != true)) {
                    this.SubmitterModuleField = value;
                    this.RaisePropertyChanged("SubmitterModule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SubmitterStackTrace {
            get {
                return this.SubmitterStackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmitterStackTraceField, value) != true)) {
                    this.SubmitterStackTraceField = value;
                    this.RaisePropertyChanged("SubmitterStackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionDetails", Namespace="http://schemas.datacontract.org/2004/07/Datapecker.DAL")]
    [System.SerializableAttribute()]
    internal partial class ExceptionDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetDeclaringTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TargetLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TargetMetadataTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetModuleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int DetailID {
            get {
                return this.DetailIDField;
            }
            set {
                if ((this.DetailIDField.Equals(value) != true)) {
                    this.DetailIDField = value;
                    this.RaisePropertyChanged("DetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TargetDeclaringType {
            get {
                return this.TargetDeclaringTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetDeclaringTypeField, value) != true)) {
                    this.TargetDeclaringTypeField = value;
                    this.RaisePropertyChanged("TargetDeclaringType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int TargetLine {
            get {
                return this.TargetLineField;
            }
            set {
                if ((this.TargetLineField.Equals(value) != true)) {
                    this.TargetLineField = value;
                    this.RaisePropertyChanged("TargetLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int TargetMetadataToken {
            get {
                return this.TargetMetadataTokenField;
            }
            set {
                if ((this.TargetMetadataTokenField.Equals(value) != true)) {
                    this.TargetMetadataTokenField = value;
                    this.RaisePropertyChanged("TargetMetadataToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TargetMethod {
            get {
                return this.TargetMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetMethodField, value) != true)) {
                    this.TargetMethodField = value;
                    this.RaisePropertyChanged("TargetMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TargetModule {
            get {
                return this.TargetModuleField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetModuleField, value) != true)) {
                    this.TargetModuleField = value;
                    this.RaisePropertyChanged("TargetModule");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionEventCase", Namespace="http://schemas.datacontract.org/2004/07/Datapecker.DAL")]
    [System.SerializableAttribute()]
    internal partial class ExceptionEventCase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime ClientRegisteredTimeUtck__BackingFieldField;
        
        private Datapecker.Agent.ReportingService.ObjectId InstanceIDk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ClientRegisteredTimeUtc>k__BackingField", IsRequired=true)]
        internal System.DateTime ClientRegisteredTimeUtck__BackingField {
            get {
                return this.ClientRegisteredTimeUtck__BackingFieldField;
            }
            set {
                if ((this.ClientRegisteredTimeUtck__BackingFieldField.Equals(value) != true)) {
                    this.ClientRegisteredTimeUtck__BackingFieldField = value;
                    this.RaisePropertyChanged("ClientRegisteredTimeUtck__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<InstanceID>k__BackingField", IsRequired=true)]
        internal Datapecker.Agent.ReportingService.ObjectId InstanceIDk__BackingField {
            get {
                return this.InstanceIDk__BackingFieldField;
            }
            set {
                if ((this.InstanceIDk__BackingFieldField.Equals(value) != true)) {
                    this.InstanceIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("InstanceIDk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectId", Namespace="http://schemas.datacontract.org/2004/07/MongoDB.Bson")]
    [System.SerializableAttribute()]
    internal partial struct ObjectId : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _incrementField;
        
        private int _machineField;
        
        private short _pidField;
        
        private int _timestampField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int _increment {
            get {
                return this._incrementField;
            }
            set {
                if ((this._incrementField.Equals(value) != true)) {
                    this._incrementField = value;
                    this.RaisePropertyChanged("_increment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int _machine {
            get {
                return this._machineField;
            }
            set {
                if ((this._machineField.Equals(value) != true)) {
                    this._machineField = value;
                    this.RaisePropertyChanged("_machine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal short _pid {
            get {
                return this._pidField;
            }
            set {
                if ((this._pidField.Equals(value) != true)) {
                    this._pidField = value;
                    this.RaisePropertyChanged("_pid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int _timestamp {
            get {
                return this._timestampField;
            }
            set {
                if ((this._timestampField.Equals(value) != true)) {
                    this._timestampField = value;
                    this.RaisePropertyChanged("_timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionTime", Namespace="http://schemas.datacontract.org/2004/07/Datapecker.Service")]
    [System.SerializableAttribute()]
    internal partial class ExceptionTime : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UtcTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EventKey {
            get {
                return this.EventKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EventKeyField, value) != true)) {
                    this.EventKeyField = value;
                    this.RaisePropertyChanged("EventKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime UtcTime {
            get {
                return this.UtcTimeField;
            }
            set {
                if ((this.UtcTimeField.Equals(value) != true)) {
                    this.UtcTimeField = value;
                    this.RaisePropertyChanged("UtcTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomEventCase", Namespace="http://schemas.datacontract.org/2004/07/Datapecker.DAL")]
    [System.SerializableAttribute()]
    internal partial class CustomEventCase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ClientRegisteredTimeUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, double> NumericPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> StringPropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime ClientRegisteredTimeUtc {
            get {
                return this.ClientRegisteredTimeUtcField;
            }
            set {
                if ((this.ClientRegisteredTimeUtcField.Equals(value) != true)) {
                    this.ClientRegisteredTimeUtcField = value;
                    this.RaisePropertyChanged("ClientRegisteredTimeUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EventKey {
            get {
                return this.EventKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EventKeyField, value) != true)) {
                    this.EventKeyField = value;
                    this.RaisePropertyChanged("EventKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.Dictionary<string, double> NumericProperties {
            get {
                return this.NumericPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.NumericPropertiesField, value) != true)) {
                    this.NumericPropertiesField = value;
                    this.RaisePropertyChanged("NumericProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.Dictionary<string, string> StringProperties {
            get {
                return this.StringPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.StringPropertiesField, value) != true)) {
                    this.StringPropertiesField = value;
                    this.RaisePropertyChanged("StringProperties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupEntry", Namespace="http://schemas.datacontract.org/2004/07/Datapecker.BL")]
    [System.SerializableAttribute()]
    internal partial class GroupEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentState", Namespace="http://schemas.datacontract.org/2004/07/Datapecker.Service")]
    [System.SerializableAttribute()]
    internal partial class AgentState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Version AgentVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDebugField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StorageWorkingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Version AgentVersion {
            get {
                return this.AgentVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentVersionField, value) != true)) {
                    this.AgentVersionField = value;
                    this.RaisePropertyChanged("AgentVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsDebug {
            get {
                return this.IsDebugField;
            }
            set {
                if ((this.IsDebugField.Equals(value) != true)) {
                    this.IsDebugField = value;
                    this.RaisePropertyChanged("IsDebug");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool StorageWorking {
            get {
                return this.StorageWorkingField;
            }
            set {
                if ((this.StorageWorkingField.Equals(value) != true)) {
                    this.StorageWorkingField = value;
                    this.RaisePropertyChanged("StorageWorking");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerUpdates", Namespace="http://schemas.datacontract.org/2004/07/Datapecker.Service")]
    [System.SerializableAttribute()]
    internal partial class ServerUpdates : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid KnownExceptionEventsTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ReportIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SettingsTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<string> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid KnownExceptionEventsToken {
            get {
                return this.KnownExceptionEventsTokenField;
            }
            set {
                if ((this.KnownExceptionEventsTokenField.Equals(value) != true)) {
                    this.KnownExceptionEventsTokenField = value;
                    this.RaisePropertyChanged("KnownExceptionEventsToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.TimeSpan ReportInterval {
            get {
                return this.ReportIntervalField;
            }
            set {
                if ((this.ReportIntervalField.Equals(value) != true)) {
                    this.ReportIntervalField = value;
                    this.RaisePropertyChanged("ReportInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid SettingsToken {
            get {
                return this.SettingsTokenField;
            }
            set {
                if ((this.SettingsTokenField.Equals(value) != true)) {
                    this.SettingsTokenField = value;
                    this.RaisePropertyChanged("SettingsToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentSettings", Namespace="http://schemas.datacontract.org/2004/07/Datapecker.Service")]
    [System.SerializableAttribute()]
    internal partial class AgentSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Datapecker.Agent.ReportingService.GroupEntry> ApplicationSettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SettingsTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<Datapecker.Agent.ReportingService.GroupEntry> ApplicationSettings {
            get {
                return this.ApplicationSettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationSettingsField, value) != true)) {
                    this.ApplicationSettingsField = value;
                    this.RaisePropertyChanged("ApplicationSettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid SettingsToken {
            get {
                return this.SettingsTokenField;
            }
            set {
                if ((this.SettingsTokenField.Equals(value) != true)) {
                    this.SettingsTokenField = value;
                    this.RaisePropertyChanged("SettingsToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KnownExceptionsState", Namespace="http://schemas.datacontract.org/2004/07/Datapecker.Service")]
    [System.SerializableAttribute()]
    internal partial class KnownExceptionsState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> EventKeysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<string> EventKeys {
            get {
                return this.EventKeysField;
            }
            set {
                if ((object.ReferenceEquals(this.EventKeysField, value) != true)) {
                    this.EventKeysField = value;
                    this.RaisePropertyChanged("EventKeys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid Token {
            get {
                return this.TokenField;
            }
            set {
                if ((this.TokenField.Equals(value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportingService.IReportService")]
    internal interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ReportException", ReplyAction="http://tempuri.org/IReportService/ReportExceptionResponse")]
        bool ReportException(Datapecker.Agent.ReportingService.ApplicationCredentials credentials, Datapecker.Agent.ReportingService.ExceptionEvent exceptionEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ReportExceptionCases", ReplyAction="http://tempuri.org/IReportService/ReportExceptionCasesResponse")]
        bool ReportExceptionCases(Datapecker.Agent.ReportingService.ApplicationCredentials credentials, System.Collections.Generic.List<Datapecker.Agent.ReportingService.ExceptionTime> cases);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ReportCustomEvents", ReplyAction="http://tempuri.org/IReportService/ReportCustomEventsResponse")]
        bool ReportCustomEvents(Datapecker.Agent.ReportingService.ApplicationCredentials credentials, System.Collections.Generic.List<Datapecker.Agent.ReportingService.CustomEventCase> cases);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ReportState", ReplyAction="http://tempuri.org/IReportService/ReportStateResponse")]
        void ReportState(Datapecker.Agent.ReportingService.ApplicationCredentials credentials, System.Collections.Generic.List<Datapecker.Agent.ReportingService.GroupEntry> customState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetServerUpdates", ReplyAction="http://tempuri.org/IReportService/GetServerUpdatesResponse")]
        Datapecker.Agent.ReportingService.ServerUpdates GetServerUpdates(Datapecker.Agent.ReportingService.ApplicationCredentials credentials, Datapecker.Agent.ReportingService.AgentState agentState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetAgentSettings", ReplyAction="http://tempuri.org/IReportService/GetAgentSettingsResponse")]
        Datapecker.Agent.ReportingService.AgentSettings GetAgentSettings(Datapecker.Agent.ReportingService.ApplicationCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetKnownExceptionEvents", ReplyAction="http://tempuri.org/IReportService/GetKnownExceptionEventsResponse")]
        Datapecker.Agent.ReportingService.KnownExceptionsState GetKnownExceptionEvents(Datapecker.Agent.ReportingService.ApplicationCredentials credentials);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IReportServiceChannel : Datapecker.Agent.ReportingService.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ReportServiceClient : System.ServiceModel.ClientBase<Datapecker.Agent.ReportingService.IReportService>, Datapecker.Agent.ReportingService.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ReportException(Datapecker.Agent.ReportingService.ApplicationCredentials credentials, Datapecker.Agent.ReportingService.ExceptionEvent exceptionEvent) {
            return base.Channel.ReportException(credentials, exceptionEvent);
        }
        
        public bool ReportExceptionCases(Datapecker.Agent.ReportingService.ApplicationCredentials credentials, System.Collections.Generic.List<Datapecker.Agent.ReportingService.ExceptionTime> cases) {
            return base.Channel.ReportExceptionCases(credentials, cases);
        }
        
        public bool ReportCustomEvents(Datapecker.Agent.ReportingService.ApplicationCredentials credentials, System.Collections.Generic.List<Datapecker.Agent.ReportingService.CustomEventCase> cases) {
            return base.Channel.ReportCustomEvents(credentials, cases);
        }
        
        public void ReportState(Datapecker.Agent.ReportingService.ApplicationCredentials credentials, System.Collections.Generic.List<Datapecker.Agent.ReportingService.GroupEntry> customState) {
            base.Channel.ReportState(credentials, customState);
        }
        
        public Datapecker.Agent.ReportingService.ServerUpdates GetServerUpdates(Datapecker.Agent.ReportingService.ApplicationCredentials credentials, Datapecker.Agent.ReportingService.AgentState agentState) {
            return base.Channel.GetServerUpdates(credentials, agentState);
        }
        
        public Datapecker.Agent.ReportingService.AgentSettings GetAgentSettings(Datapecker.Agent.ReportingService.ApplicationCredentials credentials) {
            return base.Channel.GetAgentSettings(credentials);
        }
        
        public Datapecker.Agent.ReportingService.KnownExceptionsState GetKnownExceptionEvents(Datapecker.Agent.ReportingService.ApplicationCredentials credentials) {
            return base.Channel.GetKnownExceptionEvents(credentials);
        }
    }
}
